services:
  jupyter:
    image: jupyter/scipy-notebook:python-3.11
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./requirements.txt:/tmp/requirements.txt
    command: >
      bash -c "pip install -r /tmp/requirements.txt && start-notebook.sh --NotebookApp.token=''"
  db:
    image: postgres:15.6
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"